Adding article links by community members
klaytn/awesome-klaytn pull request #10
Opened 2022-07-03 15:36 UTC by AyDeveloper

List of useful articles published on hashnode

2022-07-03 20:44 UTC, kjhman21 reviewed
Thanks a lot!

2022-07-03 23:23 UTC, kjhman21 approved these changes

2022-07-03 23:23 UTC, kjhman21 commented on README.md
> +](https://oxpampam.hashnode.dev/beginners-guide-on-how-to-add-klaytn-to-metamask)
```suggestion
* [Beginner's guide on how to add Klaytn to Metamask](https://oxpampam.hashnode.dev/beginners-guide-on-how-to-add-klaytn-to-metamask)
```

2022-07-03 23:24 UTC, kjhman21 requested changes
Need to fix to remove a line break.

2022-07-04 07:15 UTC, terrikwak approved these changes

2022-07-04 10:35 UTC, AyDeveloper commented on README.md
> +](https://oxpampam.hashnode.dev/beginners-guide-on-how-to-add-klaytn-to-metamask)
Alright would fix that ASAP

2022-07-05 06:15 UTC, kjhman21 approved these changes

2022-07-05 06:16 UTC, merged